export const ACTION = {
    LOADING : 'LOADING',
    ERROR: 'ERROR_FOUND',
    FETCH_MEALS: 'FETCH_MEALS',
    UPDATE_MEAL: 'UPDATE_MEAL',
    REMOVE_MEAL: 'REMOVE_MEAL',
    LOGIN: 'LOGIN',
    SELECTED_MEAL:'SELECTED_MEAL',
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    LOADED: 'LOADED'
}